# Generated by Django 2.0.5 on 2018-05-28 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Имя анализа')),
                ('WS', models.CharField(max_length=20, verbose_name='Сигнал скорости ветра')),
                ('WD', models.CharField(max_length=20, verbose_name='Сигнал направления ветра')),
                ('WD_Step', models.FloatField(default=0, verbose_name='Шаг группировки направления')),
                ('WD_Start', models.FloatField(default=0, verbose_name='Начало сектора направления')),
                ('WD_Stop', models.FloatField(default=0, verbose_name='Конец сектора направления')),
                ('WS_Start', models.FloatField(default=0, verbose_name='Начало диапазона скорости')),
                ('WS_Stop', models.FloatField(default=0, verbose_name='Конец диапазона скорости')),
                ('Date_Create', models.DateField(default=django.utils.timezone.now)),
                ('Date_Modified', models.DateField(default=django.utils.timezone.now)),
                ('File_Data', models.FileField(default='', upload_to='upload_data')),
                ('File_Zip', models.FileField(default='', upload_to='downloads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анализ',
                'ordering': ['Date_Modified'],
            },
        ),
    ]
